import { doGetAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Data {
  clientName: string | null;
  fileNumber: string | null;
  caseworker: string | null;
  date: string | null;
  status: string | null;
}

// Empty Data
const emptyData: Data = {
  clientName: null,
  fileNumber: null,
  caseworker: null,
  date: null,
  status: null,
};

export interface State {
  data: Data;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, Data>(
  "search/doGet",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doGetAPI(formData, store.login.jwtToken);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const searchSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "search",
  initialState: {
    data: emptyData,
    status: "none",
  },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.status = "none";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { cleanState } = searchSlice.actions;

export default searchSlice.reducer;
