import { doGetAPI, doPostAPI, doRemoveAPI, doSearchAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Data {
  cgReminderId: number;
  id: number;
  referenceId: any;
  reminderDto: {
    reminderId: number;
    assignedTo: string;
    regarding: any;
    subject: string;
    status: string;
    reminderDate: string;
    endDate: string;
    description: string;
    frequency: string;
  };
}

export interface GetData {
  cgReminderId: number;
  id: number;
  participantId: number;
  referenceId: any;
  reminderDto: {
    reminderId: number;
    assignedTo: string;
    regarding: any;
    subject: string;
    status: string;
    reminderDate: string;
    endDate: string;
    description: string;
    frequency: string;
  };
}
// Empty Data
const emptyGetData: GetData = {
  cgReminderId: 0,
  id: 0,
  referenceId: 0,
  participantId: 0,
  reminderDto: {
    reminderId: 0,
    assignedTo: "",
    regarding: "",
    subject: "",
    status: "",
    reminderDate: "",
    endDate: "",
    description: "",
    frequency: "",
  },
};
const emptyData: Data = {
  cgReminderId: 0,
  id: 0,
  referenceId: 0,
  reminderDto: {
    reminderId: 0,
    assignedTo: "",
    regarding: "",
    subject: "",
    status: "",
    reminderDate: "",
    endDate: "",
    description: "",
    frequency: "",
  },
};

export interface State {
  clientName: string;
  click: boolean;
  id: number;
  record: Data[];
  record1:Data[];
  getData: GetData;
  data: Data;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, number>(
  "caregiverReminderservice/doGet",
  async (cgReminderId, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doGetAPI(cgReminderId, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<Data[], Data>(
  "caregiverReminderservice/doPost",
  async (formData: Data, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doPostAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doRemove = createAsyncThunk<Data, number>(
  "caregiverReminderservice/doRemove",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doRemoveAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doSearch = createAsyncThunk<Data[], any>(
  "caregiverReminderservice/doSearch",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doSearchAPI(
      formData.id,
      formData.data || null,
      store.login.token
    );

    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const cgReminderSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "cgReminder",
  initialState: {
    clientName: "",
    id: 0,
    click: false,
    record: [],
    record1:[],
    data: emptyData,
    getData: emptyGetData,
    status: "failed",
  },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.getData = emptyGetData;
      state.record = [];
      state.record1=[];
      state.status = "none";
      state.click = false;
      state.clientName = "";
      state.id = 0;
    },
    setClick(state, action) {
      state.click = action.payload;
    },
    setCgReminderClientName(state, action) {
      state.clientName = action.payload;
      state.getData.reminderDto.regarding = action.payload;
    },
    setCgReminderParticipantId(state, action) {
      state.id = action.payload;
      state.getData.participantId = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })

      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        // state.data = action.payload;
        state.record1=action.payload;
        state.getData.cgReminderId = action.payload[0].cgReminderId;

        state.getData.id = action.payload[0].id;
        state.getData.reminderDto.assignedTo =
          action.payload[0].reminderDto.assignedTo;
        state.getData.reminderDto.description =
          action.payload[0].reminderDto.description;
        state.getData.reminderDto.endDate = action.payload[0].reminderDto.endDate;
        state.getData.reminderDto.frequency =
          action.payload[0].reminderDto.frequency;
        state.getData.reminderDto.regarding =
          action.payload[0].reminderDto.regarding;
        state.getData.reminderDto.status = action.payload[0].reminderDto.status;
        state.getData.reminderDto.subject = action.payload[0].reminderDto.subject;
        state.getData.reminderDto.reminderDate =
          action.payload[0].reminderDto.reminderDate;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doSearch.fulfilled, (state, action) => {
        state.record = action.payload;
        state.status = "success";
      })
      .addCase(doSearch.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doSearch.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doRemove.fulfilled, (state, action) => {
        state.status = "success";
      })
      .addCase(doRemove.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doRemove.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const {
  disableClosingDate,
  enableClosingDate,
  cleanState,
  setName,
  setClick,
  setCgReminderClientName,
  setCgReminderParticipantId,
} = cgReminderSlice.actions;

export default cgReminderSlice.reducer;
