import { doGetAPI, doPostAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { RootState } from "../../../library/store";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Caregiver {
  id: number;
  cgCaregiverId: number;
  bgCheckStatus: string;
  date: string;
  details: string;
  trainingsCompleted: string;
}

const emptyCaregiver: Caregiver = {
  id: 0,
  cgCaregiverId: 0,
  bgCheckStatus: "",
  date: "",
  details: "",
  trainingsCompleted: "",
};

export interface CaregiversDetails {
  id: number;
  cgCareProviderId: number;
  priCaregiver: Caregiver;
  secCaregiver: Caregiver;
}

const emptyCaregiverDetails: CaregiversDetails = {
  id: 0,
  cgCareProviderId: 0,
  priCaregiver: emptyCaregiver,
  secCaregiver: emptyCaregiver,
};

export interface State {
  data: CaregiversDetails;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<CaregiversDetails, number>(
  "caregivers/doGet",
  async (cgCareProviderId, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doGetAPI(
      cgCareProviderId,
      store.login.token
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<CaregiversDetails, CaregiversDetails>(
  "caregivers/doPost",
  async (formData: CaregiversDetails, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doPostAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const caregiversSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "caregivers",
  initialState: { data: emptyCaregiverDetails, status: "none" },
  reducers: {
    cleanState(state) {
      state.data = emptyCaregiverDetails;
      state.status = "none";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { clean } = caregiversSlice.actions;

export default caregiversSlice.reducer;
