import { doGetAPI, doPostAPI, doSearchAPI, doRemoveAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface GetData1 {
  participantId: number;
     
  participantReminderId: number;

    reminderId: number;
    assignedTo: string;
    regarding: any;
    subject: string;
    status: string;
    reminderDate: string;
    endDate: string;
    description: string;
    frequency: string;
  
}
const emptyGetData1: GetData1 = {
  participantId: 0,
  participantReminderId: 0,
  
    reminderId: 0,
    assignedTo: "",
    regarding: "",
    subject: "",
    status: "",
    reminderDate: "",
    endDate: "",
    description: "",
    frequency: "",
  
};
export interface Data {
  participantId: number;

  participantReminderId: number;
  reminderDto: {
    reminderId: number;
    assignedTo: string;
    regarding: any;
    subject: string;
    status: string;
    reminderDate: string;
    endDate: string;
    description: string;
    frequency: string;
  };
}
// Empty Data
const emptyData: Data = {
  participantId: 0,
  participantReminderId: 0,
  reminderDto: {
    reminderId: 0,
    assignedTo: "",
    regarding: "",
    subject: "",
    status: "",
    reminderDate: "",
    endDate: "",
    description: "",
    frequency: "",
  },
};

export interface GetData {
  participantId: number;
  id: number;
  participantReminderId: number;
  reminderDto: {
    reminderId: number;
    assignedTo: string;
    regarding: any;
    subject: string;
    status: string;
    reminderDate: string;
    endDate: string;
    description: string;
    frequency: string;
  };
}
const emptyGetData: GetData={
  participantId:0,
  id:0,
  participantReminderId: 0,
  reminderDto: {
    reminderId: 0,
    assignedTo: "",
    regarding: "",
    subject: "",
    status: "",
    reminderDate: "",
    endDate: "",
    description: "",
    frequency: "",
  }
}



export interface State {
  data: Data;
  click: boolean;
  clientName: string;
  id: number;
  record: Data[];
  record1: Data[];
  record2:GetData1[];
  getData: GetData;
  getData1:GetData1;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, number>(
  "participantserviceReminder/doGet",
  async (participantReminderId, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doGetAPI(
      participantReminderId,
      store.login.token
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<Data[], Data>(
  "participantserviceReminder/doPost",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doPostAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);
export const doRemove = createAsyncThunk<Data, number>(
  "participantserviceReminder/doRemove",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doRemoveAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);
export const doSearch = createAsyncThunk<GetData1[], any>(
  "participantserviceReminder/doSearch",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doSearchAPI(
      formData.id,
      formData.data || null,
      store.login.token
    );

    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const contactSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "cyfmsreminder",
  initialState: {
    data: emptyData,
    clientName: "",
    record: [],
    id: 0,
    getData: emptyGetData,
    getData1:emptyGetData1,
    click: false,
    record1: [],
    record2:[],
    status: "failed",
  },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.status = "none";
      state.clientName = "";
      state.id = 0;
      state.record = [];
      state.record1 = [];
      state.record2=[];
      state.click = false;
      state.getData = emptyGetData;
      state.getData1=emptyGetData1;
    },
    setClick(state, action) {
      state.click = action.payload;
    },
    setCyfmsReminderClientName(state, action) {
      state.clientName = action.payload;
      state.getData.reminderDto.regarding = action.payload;
    },
    setCyfmsReminderParticipantId(state, action) {
      state.id = action.payload;
      state.getData.participantId = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        // state.data = action.payload;
        state.record1 = action.payload;
        state.getData.participantId = action.payload[0].participantId;
        state.getData.participantReminderId =
          action.payload[0].participantReminderId;
        state.getData.reminderDto.assignedTo =
          action.payload[0].reminderDto.assignedTo;
        state.getData.reminderDto.description =
          action.payload[0].reminderDto.description;
        state.getData.reminderDto.endDate =
          action.payload[0].reminderDto.endDate;
        state.getData.reminderDto.frequency =
          action.payload[0].reminderDto.frequency;
        state.getData.reminderDto.regarding =
          action.payload[0].reminderDto.regarding;
        state.getData.reminderDto.status = action.payload[0].reminderDto.status;
        state.getData.reminderDto.subject =
          action.payload[0].reminderDto.subject;
        state.getData.reminderDto.reminderDate =
          action.payload[0].reminderDto.reminderDate;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doRemove.fulfilled, (state, action) => {
        state.status = "success";
      })
      .addCase(doRemove.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doRemove.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doSearch.fulfilled, (state, action) => {
        state.record2 = action.payload;
        state.status = "success";
      })
      .addCase(doSearch.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doSearch.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const {
  cleanState,
  setName,
  setClick,
  setCyfmsReminderClientName,
  setCyfmsReminderParticipantId,
} = contactSlice.actions;

export default contactSlice.reducer;
