server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/twn
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: gigatorb

codetablevalues:
  gender:
    DEFAULT:
      "en": ""
      "fr": ""
    MALE:
      "en": "Male"
      "fr": "Masculin"
    FEMALE:
      "en": "Female"
      "fr": "Féminin"
    LGBTQ:
      "en": "LGBTQ"
      "fr": "LGBTQ"

  maritalStatus:
    DEFAULT:
      "en": ""
      "fr": ""
    MARRIED:
      "en": "Married"
      "fr": "Marry"
    UNMARRIED:
      "en": "Unmarried"
      "fr": "unmarry"
    DIVORCE:
      "en": "Divorced"
      "fr": "Divorce"
  role:
    DEFAULT:
      "en": ""
      "fr": ""
    COUNSELOR:
      "en": "Counselor"
      "fr": "Coun"
    CFSWORKER:
      "en": "CFSworker"
      "fr": "Cfs"

  education:
    DEFAULT:
      "en": ""
      "fr": ""
    NO:
      "en": "No"
      "fr": "No"
    YES:
      "en": "Yes"
      "fr": "Yes"
    MAYBE:
      "en": "Maybe"
      "fr": "Maybe"

  typeOFEmployee:
    DEFAULT:
      "en": ""
      "fr": ""
    FULLTIME:
      "en": "Full-Time"
      "fr": "FullTime"
    PARTTIME:
      "en": "Part-Time"
      "fr": "PartTime"
    Casual:
      "en": "Casual"
      "fr": "Casual"
    JOBSEARCH:
      "en": "Job Search"
      "fr": "Job search"
