server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:sqlserver://cyfwmstwn-server.database.windows.net:1433;database=cyfwmsdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin1
    password: Password@123
  profiles:
    include:
      - participant
      - initialContact
      - culturalProgAndAct
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      platform: mysql
      mode: always
jwt:
  secret: gigatorb
