server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:sqlserver://cyfwms-twn.database.windows.net:1433;database=cyfwmsdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin1
    password: Password@123

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: gigatorb

codetablevalues:
  gender:
    MALE:
      "en": "Male"
      "fr": "Mâle"
    FEMALE:
      "en": "Female"
      "fr": "Femelle"
    LGBTQ:
      "en": "LGBTQ"
      "fr": "LGBTQ"

  maritalStatus:
    MARRIED:
      "en": "Married"
      "fr": "Marié"
    UNMARRIED:
      "en": "Unmarried"
      "fr": "Célibataire"
    DIVORCE:
      "en": "Divorced"
      "fr": "Divorcé"

  province:
    DEFAULT:
      "en": "British Columbia"
      "fr": "Colombie britannique"
    ALBERTA:
      "en": "Alberta"
      "fr": "Alberta"
    BRITISHCOLUMBIA:
      "en": "British Columbia"
      "fr": "Colombie britannique"
    MANITOBA:
      "en": "Manitoba"
      "fr": "Manitoba"
    NEWBRUNSWICK:
      "en": "New Brunswick"
      "fr": "Nouveau-Brunswick"
    NEWFOUNDLANDANDLABRADOR:
      "en": "Newfoundland and Labrador"
      "fr": "Terre Neuve et Labrador"
    NORTHWESTTERRITORIES:
      "en": "Northwest Territories"
      "fr": "Territoires du nord-ouest"
    NOVASCOTIA:
      "en": "Nova Scotia"
      "fr": "Nouvelle Écosse"
    NUNAVUT:
      "en": "Nunavut"
      "fr": "Nunavut"
    ONTARIO:
      "en": "Ontario"
      "fr": "Ontario"
    PRINCEEDWAEDISLAND:
      "en": "Prince Edward Island"
      "fr": "Île du Prince Édouard"
    QUEBEC:
      "en": "Quebec"
      "fr": "Québec"
    SASKATCHEWAN:
      "en": "Saskatchewan"
      "fr": "Saskatchewan"
    YUKON:
      "en": "Yukon"
      "fr": "Yukon"
  role:
    COUNSELOR:
      "en": "Counselor"
      "fr": "Conseiller"
    CFSWORKER:
      "en": "CFS Worker"
      "fr": "CFS Ouvrier"

  education:
    YES:
      "en": "Yes"
      "fr": "Oui"
    NO:
      "en": "No"
      "fr": "Non"
    MAYBE:
      "en": "Maybe"
      "fr": "Peut-être"

  typeOFEmployee:
    FULLTIME:
      "en": "Full-Time"
      "fr": "Plein temps"
    PARTTIME:
      "en": "Part-Time"
      "fr": "Temps partiel"
    Casual:
      "en": "Casual"
      "fr": "Décontracté"
    JOBSEARCH:
      "en": "Job Search"
      "fr": "Recherche d'emploi"

  initialContactStatus:
    PROGRESS:
      "en": "In Progress"
      "fr": "En Cours"
    ACTIVE:
      "en": "Active"
      "fr": "Actif"
    CLOSED:
      "en": "Closed"
      "fr": "Fermé"

  initialContactReferral:
    YES:
      "en": "Yes"
      "fr": "Oui"
    No:
      "en": "No"
      "fr": "Non"

  presentConcerns:
    HEALTH:
      "en": "Health"
      "fr": "Santé"
    ADDICTION:
      "en": "Addiction"
      "fr": "Dépendance"
    ABUSE:
      "en": "Abuse"
      "fr": "Abuser de"
    LEGAL:
      "en": "Legal"
      "fr": "Juridique"
    EMLOYMENT:
      "en": "Employment"
      "fr": "Emploi"
    EDUCATION:
      "en": "Education"
      "fr": "Éducation"
    PARENTING:
      "en": "Parenting"
      "fr": "Parentalité"
    RELATIONSHIPS:
      "en": "Relationships"
      "fr": "Des relations"
    FINANCIAL:
      "en": "Financial"
      "fr": "Financier"
  mentalHealthOrSubstanceAbuse:
    ALCOHOL:
      "en": "Alcohol"
      "fr": "De l'alcool"
    DRUGS:
      "en": "Drugs"
      "fr": "Drogues"
    NARCOTIC:
      "en": "Narcotic"
      "fr": "Narcotique"
    PILLS:
      "en": "Pills"
      "fr": "Pilules"
    SOLVANTS:
      "en": "Solvants"
      "fr": "Solvants"
    GAMBLING:
      "en": "Gambling"
      "fr": "Jeux d'argent"
    OTHER:
      "en": "Other"
      "fr": "Autre"
  typeOfPatient:
    OUTPATIENT:
      "en": "Outpatient"
      "fr": "Ambulatoire"
    INPATIENT:
      "en": "Inpatient"
      "fr": "Hospitalisé"

  risk:
    LOW:
      "en": "Low"
      "fr": "Bas"
    MEDIUM:
      "en": "Medium"
      "fr": "Moyen"
    HIGH:
      "en": "High"
      "fr": "haut"
