reflectoring:
  trace: true
server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  messages:
    basename: lang/res
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:mysql://mysql-twn-server.mysql.database.azure.com:3306/twnmysqldb
    username: admin1
    password: Password@123
  profiles:
    include:
      - participant
      - initialContact
      - culturalProgAndAct
      - caregivers
      - appointment
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true

  #sql:
  #  init:
  #    platform: mysql
  #    mode: always
jwt:
  secret: gigatorb
