server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:sqlserver://cyfwms-twn-server.database.windows.net:1433;database=cyfwmsdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin1
    password: Password@123

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: gigatorb

codetablevalues:
  gender:
    MALE:
      "en": "Male"
      "fr": "Masculin"
    FEMALE:
      "en": "Female"
      "fr": "Féminin"
    LGQTB:
      "en": "LGQTB"
      "fr": "LGQTB"

  maritalStatus:
    MARRIED:
      "en": "Married"
      "fr": "Marry"
    UNMARRIED:
      "en": "Unmarried"
      "fr": "unmarry"
    DIVORCE:
      "en": "Divorce"
      "fr": "Divorce"
  role:
    COUNSELOR:
      "en": "Counselor"
      "fr": "Coun"
    CFSWORKER:
      "en": "CFSworker"
      "fr": "Cfs"

  education:
    NO:
      "en": "No"
      "fr": "No"
    YES:
      "en": "Yes"
      "fr": "Yes"
    MAYBE:
      "en": "Maybe"
      "fr": "Maybe"

  typeOFEmployee:
    FULLTIME:
      "en": "FullTime"
      "fr": "FullTime"
    PARTTIME:
      "en": "PartTime"
      "fr": "PartTime"

    CASUAL:
      "en": "Casual"
      "fr": "Casual"

    JOBSEARCH:
      "en": "Job search"
      "fr": "Job search"
