appointment:
  appointmentStatus:
    SCHEDULED:
      "en": "Scheduled"
      "fr": "Programmé"
    RESCHEDULED:
      "en": "Rescheduled"
      "fr": "reporté"
    COMPLETED:
      "en": "Completed"
      "fr": "Complété"
    CANCELLED:
      "en": "Cancelled"
      "fr": "Annulé"
    MISSED:
      "en" : "Missed"
      "fr" : "Manqué"
  frequency:
    DAILY:
      "en": "Daily"
      "fr": "du quotidien"
    WEEKLY:
      "en": "Weekly"
      "fr": "hebdomadaire"
    BI-WEEKLY:
      "en": "Bi-weekly"
      "fr": "bihebdomadaire"
    MONTHLY:
      "en": "Monthly"
      "fr": "mensuelle"