server:
  port: 9088
#This is to avoid Swagger related version issues
spring:
  application:
    name: TWN-SERVER
  datasource:
    url: jdbc:sqlserver://cyfwms-twn-server.database.windows.net:1433;database=cyfwmsdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin1
    password: Password@123

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: gigatorb

codetablevalues:
  gender:
    DEFAULT:
      "en": ""
      "fr": ""
    MALE:
      "en": "Male"
      "fr": "Masculin"
    FEMALE:
      "en": "Female"
      "fr": "Féminin"
    LGBTQ:
      "en": "LGBTQ"
      "fr": "LGBTQ"

  maritalStatus:
    DEFAULT:
      "en": ""
      "fr": ""
    MARRIED:
      "en": "Married"
      "fr": "Marry"
    UNMARRIED:
      "en": "Unmarried"
      "fr": "unmarry"
    DIVORCE:
      "en": "Divorced"
      "fr": "Divorce"
  role:
    DEFAULT:
      "en": ""
      "fr": ""
    COUNSELOR:
      "en": "Counselor"
      "fr": "Coun"
    CFSWORKER:
      "en": "CFSworker"
      "fr": "Cfs"

  education:
    DEFAULT:
      "en": ""
      "fr": ""
    YES:
      "en": "Yes"
      "fr": "Yes"
    NO:
      "en": "No"
      "fr": "No"
    MAYBE:
      "en": "Maybe"
      "fr": "Maybe"

  typeOFEmployee:
    DEFAULT:
      "en": ""
      "fr": ""
    FULLTIME:
      "en": "Full-Time"
      "fr": "FullTime"
    PARTTIME:
      "en": "Part-Time"
      "fr": "PartTime"
    Casual:
      "en": "Casual"
      "fr": "Casual"
    JOBSEARCH:
      "en": "Job Search"
      "fr": "Job search"

  initialContactStatus:
    DEFAULT:
      "en": ""
      "fr": ""
    PROGRESS:
      "en": "In Progress"
      "fr": "In Progress"
    CLOSED:
      "en": "Closed"
      "fr": "Closed"


  initialContactReferral:
    DEFAULT:
      "en": ""
      "fr": ""
    YES:
      "en": "Yes"
      "fr": "Yes"
    No:
      "en": "No"
      "fr": "No"


  presentConcerns:
     DEFAULT:
      "en": ""
      "fr": ""
     HEALTH:
      "en": "Health"
      "fr": "Health"
     ADDICTION:
      "en": "Addiction"
      "fr": "Addiction"
     ABUSE:
      "en": "Abuse"
      "fr": "Abuse"


  mentalHealthOrSubstanceAbuse:
    DEFAULT:
      "en": ""
      "fr": ""
    ALCOHOL:
      "en": "Alcohol"
      "fr": "Alcohol"
    DRUGS:
      "en": "Drugs"
      "fr": "Drugs"
    NARCOTIC:
      "en": "Narcotic"
      "fr": "Narcotic"


  typeOfPatient:
    DEFAULT:
      "en": ""
      "fr": ""
    OUTPATIENT:
      "en": "Outpatient"
      "fr": "Outpatient"
    INPATIENT:
      "en": "Inpatient"
      "fr": "Inpatient"

  risk:
    DEFAULT:
      "en": ""
      "fr": ""
    LOW:
      "en": "Low"
      "fr": "Low"
    MEDIUM:
      "en": "Medium"
      "fr": "Medium"
    HIGH:
      "en": "High"
      "fr": "High"



