server:
  port: 9088

spring:
  application:
    name: UCEP-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/twn?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
jwt:
  secret: gigatorb

codetablevalues:
  gender:
    MALE:
      "en" : "Male"
      "fr" : "Masculin"
    FEMALE:
      "en": "Female"
      "fr": "Féminin"
    LGQTB:
      "en": "LGQTB"
      "fr": "LGQTB"
