import { doGetAPI, doPostAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../../library/store";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Data {
  culturalProgramId: 0;
  referenceId: number;
  name: string;
  type: string;
  status: string;
  caseworker: string;
  startDate: string;
  endDate: string;
  totalCost: number;
  totalParticipation: number;
  sessionDetails: string;
  costOrParticipationDetails: string;
  outcomes: string;
  notes: string;
}

// Empty Data
const emptyData: Data = {
  culturalProgramId: 0,
  referenceId: 0,
  name: "",
  type: "",
  status: "",
  caseworker: "",
  startDate: "",
  endDate: "",
  totalCost: 0,
  totalParticipation: 0,
  sessionDetails: "",
  costOrParticipationDetails: "",
  outcomes: "",
  notes: "",
};

export interface State {
  data: Data;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, number>(
  "cpa/doGet",
  async (culturalProgramId, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doGetAPI(
      culturalProgramId,
      store.login.token
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<Data, Data>(
  "cpa/doPost",
  async (formData: Data, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doPostAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const cpaSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "cpa",
  initialState: { data: emptyData, status: "none" },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.status = "none";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { cleanState } = cpaSlice.actions;

export default cpaSlice.reducer;
