import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { doLoginAPI } from "./loginAPI";
import type { AxiosResponse } from "axios";
import jwt from "jwt-decode";

export interface LoginData {
  username: string;
  password: string;
}

export interface LoginState {
  isLoggedIn: boolean;
  status: "failed" | "loading" | "success";
}

export const doLogin = createAsyncThunk(
  "login/doLogin",
  async (data: LoginData, { dispatch }) => {
    const res: AxiosResponse = await doLoginAPI(data);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const loginSlice = createSlice({
  name: "login",
  initialState: {
    isLoggedIn: false,
    status: "failed",
  },
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(doLogin.fulfilled, (state, action) => {
      try {
        const decodedPayload: any = jwt(action.payload);
        console.log(decodedPayload);
      } catch (err) {
        console.log(err);
      }
      state.isLoggedIn = true;
      state.status = "success";
    });
    builder.addCase(doLogin.pending, (state) => {
      state.status = "loading";
    });
    builder.addCase(doLogin.rejected, (state) => {
      state.status = "failed";
    });
  },
});

export const {} = loginSlice.actions;

export default loginSlice.reducer;
