import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";
import { doGetCriminalHistoryAPI, doPostCriminalHistoryAPI } from "./criminalhistoryAPI";

export interface CriminalHistoryGetData {
    user:{ 
       
    }
}
export interface CriminalHistoryPostData {
  user: {};
}

export interface CriminalHistoryGetState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}
export interface CriminalHistoryPostState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doGetCriminalHistory = createAsyncThunk(
    "criminalhistory/doGetCriminalHistory",
    async (data: CriminalHistoryGetData, { dispatch, getState }) => {
    const res: AxiosResponse = await doGetCriminalHistoryAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPostCriminalHistory= createAsyncThunk(
  "criminalhistory/doPostCriminalHistory",
  async (data: CriminalHistoryPostData, { dispatch, getState }) => {
    const res: AxiosResponse = await doPostCriminalHistoryAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    console.log("criminal",data)
    return res.data;
  }
);

export const criminalhistorySlice = createSlice({
  name: "criminalhistory",
  initialState: {
    participantId: 0,
    user: { 
        participantId: 0,
        criminalHistoryId:0,
        probation: "",
        parole: "",
        conditions: "",
        courtWorkerAndContactInfo: "",
        criminalHistoryRecordList:""
    },
    jwtToken: "",
    status: "failed",
  },
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGetCriminalHistory.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doGetCriminalHistory.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGetCriminalHistory.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPostCriminalHistory.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doPostCriminalHistory.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPostCriminalHistory.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const {} = criminalhistorySlice.actions;

export default criminalhistorySlice.reducer;
