import {
  doGetFamilyPhysiciansAPI,
  doPostFamilyPhysiciansAPI,
} from "./familyPhysiciansAPI";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface FamilyPhysiciansGetData {
  readData: {};
}

export interface FamilyPhysiciansGetState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doGetFamilyPhysicians = createAsyncThunk(
  "familyPhysicians/doGetFamilyPhysicians",
  async (data: FamilyPhysiciansGetData, { dispatch, getState }) => {
    const res: AxiosResponse = await doGetFamilyPhysiciansAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export interface FamilyPhysiciansPostData {
  user: {};
}

export interface FamilyPhysiciansPostState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doPostFamilyPhysicians = createAsyncThunk(
  "familyPhysicians/doPostFamilyPhysicians",
  async (data: FamilyPhysiciansPostData, { dispatch, getState }) => {
    const res: AxiosResponse = await doPostFamilyPhysiciansAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const familyPhysiciansSlice = createSlice({
  name: "familyPhysicians",
  initialState: {
    participantId: 0,
    readData: [],
    user: {
      participantId: 0,
      familyPhysicianId: 0,
      name: "",
      phone: "",
      cell: "",
      listOfMedication: "",
    },
    jwtToken: "",
    status: "failed",
  },
  reducers: {
    cleanFamilyPhysiciansState(state: any) {
      state.participantId = 0;
      state.readData = [];
      state.user = { educationId: 0 };
      state.jwtToken = "";
      state.status = "failed";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGetFamilyPhysicians.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.readData = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doGetFamilyPhysicians.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGetFamilyPhysicians.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPostFamilyPhysicians.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doPostFamilyPhysicians.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPostFamilyPhysicians.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { cleanFamilyPhysiciansState } = familyPhysiciansSlice.actions;

export default familyPhysiciansSlice.reducer;
