import { doGetAPI, doPostAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Data {
  participantId: number;
  participantContactId: number;
  addressLine1: string;
  addressLine2: string;
  city: string;
  province: string;
  postalCode: string;
  homePhone: string;
  workPhone: string;
  cellPhone: string;
  emailAddress: string;
}

// Empty Data
const emptyData: Data = {
  participantId: 0,
  participantContactId: 0,
  addressLine1: "",
  addressLine2: "",
  city: "",
  province: "",
  postalCode: "",
  homePhone: "",
  workPhone: "",
  cellPhone: "",
  emailAddress: "",
};

export interface State {
  data: Data;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, number>(
  "contact/doGet",
  async (participantID, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doGetAPI(
      participantID,
      store.login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<Data, Data>(
  "contact/doPost",
  async (formData, { getState }) => {
    const store: any = getState();
    const res: AxiosResponse = await doPostAPI(formData, store.login.jwtToken);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const contactSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "contact",
  initialState: { data: emptyData, status: "none" },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.status = "none";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { cleanState } = contactSlice.actions;

export default contactSlice.reducer;
