import { doGetAPI, doPostAPI } from "./api";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../../library/store";
import type { SliceCaseReducers } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface Data {
  id: number;
  refId: number;
  name: string;
  status: string;
  type: string;
  otherType: string;
  address: string;
  city: string;
  postalCode: string;
  province: string;
  phoneNum: string;
  email: string;
  priCaregiver: string;
  secCaregiver: string;
}

// Empty Data
const emptyData: Data = {
  id: 0,
  refId: 0,
  name: "",
  status: "",
  type: "",
  otherType: "",
  address: "",
  city: "",
  postalCode: "",
  province: "",
  phoneNum: "",
  email: "",
  priCaregiver: "",
  secCaregiver: "",
};

export interface State {
  data: Data;
  status: "failed" | "none" | "loading" | "success";
}

export const doGet = createAsyncThunk<Data, number>(
  "careProvider/doGet",
  async (id, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doGetAPI(id, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPost = createAsyncThunk<Data, Data>(
  "careProvider/doPost",
  async (formData: Data, { getState }) => {
    const store = getState() as RootState;
    const res: AxiosResponse = await doPostAPI(formData, store.login.token);
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const careProviderSlice = createSlice<State, SliceCaseReducers<State>>({
  name: "careProvider",
  initialState: { data: emptyData, status: "none" },
  reducers: {
    cleanState(state) {
      state.data = emptyData;
      state.status = "none";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGet.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doGet.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGet.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPost.fulfilled, (state, action) => {
        state.data = action.payload;
        state.status = "success";
      })
      .addCase(doPost.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPost.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { clean } = careProviderSlice.actions;

export default careProviderSlice.reducer;
