import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";
import { doGetHouseHoldAPI, doPostHouseHoldAPI } from "./householdAPI";

export interface HouseHoldGetData {
  user: {};
}
export interface HouseHoldPostData {
  user: {};
}

export interface HouseHoldGetState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}
export interface HouseHoldPostState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doGetHouseHold = createAsyncThunk(
  "household/doGetHouseHold",
  async (data: HouseHoldGetData, { dispatch, getState }) => {
    const res: AxiosResponse = await doGetHouseHoldAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const doPostHouseHold = createAsyncThunk(
  "household/doPostHouseHold",
  async (data: HouseHoldPostData, { dispatch, getState }) => {
    const res: AxiosResponse = await doPostHouseHoldAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const householdSlice = createSlice({
  name: "household",
  initialState: {
    participantId: 0,
    user: {
      participantId: 0,
      householdMemberId: 0,
      name: "",
      gender: "",
      dateOfBirth: "",
      residing: "",
    },
    jwtToken: "",
    status: "failed",
  },
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGetHouseHold.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doGetHouseHold.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGetHouseHold.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPostHouseHold.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doPostHouseHold.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPostHouseHold.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const {} = householdSlice.actions;

export default householdSlice.reducer;
