import {
  doGetCYFMSCounselorsAPI,
  doPostCYFMSCounselorsAPI,
} from "./cyfmsCounselorsAPI";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import type { AxiosResponse } from "axios";

export interface CYFMSCounselorsGetData {
  user: {};
}

export interface CYFMSCounselorsGetState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doGetCYFMSCounselors = createAsyncThunk(
  "cyfmsCounselors/doGetCYFMSCounselors",
  async (data: CYFMSCounselorsGetData, { dispatch, getState }) => {
    const res: AxiosResponse = await doGetCYFMSCounselorsAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export interface CYFMSCounselorsPostData {
  user: {};
}

export interface CYFMSCounselorsPostState {
  jwtToken: string;
  status: "failed" | "loading" | "success";
}

export const doPostCYFMSCounselors = createAsyncThunk(
  "cyfmsCounselors/doPostCYFMSCounselors",
  async (data: CYFMSCounselorsPostData, { dispatch, getState }) => {
    const res: AxiosResponse = await doPostCYFMSCounselorsAPI(
      data,
      (getState() as any).login.jwtToken
    );
    // Becomes the `fulfilled` action payload:
    return res.data;
  }
);

export const cyfmsCounselorsSlice = createSlice({
  name: "cyfmsCounselors",
  initialState: {
    participantId: 0,
    user: {
      participantId: 0,
      counselorCFSWorkerId: 0,
      role: "",
      name: "",
      contactInformation: "",
    },
    jwtToken: "",
    status: "failed",
  },
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(doGetCYFMSCounselors.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doGetCYFMSCounselors.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doGetCYFMSCounselors.rejected, (state) => {
        state.status = "failed";
      });
    builder
      .addCase(doPostCYFMSCounselors.fulfilled, (state, action) => {
        try {
          //const decodedPayload: any = jwt(action.payload.jwtToken);
          state.user = action.payload;
        } catch (err) {
          console.log(err);
        }

        state.status = "success";
      })
      .addCase(doPostCYFMSCounselors.pending, (state) => {
        state.status = "loading";
      })
      .addCase(doPostCYFMSCounselors.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const {} = cyfmsCounselorsSlice.actions;

export default cyfmsCounselorsSlice.reducer;
